#!/bin/bash

export WINEPREFIX=/home/container/.wine32
export WINEARCH=win32
BASEDIR=$WINEPREFIX/drive_c/Dynamix/Tribes2/GameData
ADMINPREFS=$BASEDIR/Classic/scripts/autoexec/AdminPrefs.cs

if [[ ! -f "$ADMINPREFS" ]]
then
  echo "Update Admin & Server Prefs..."
  /home/container/cfg-admin-prefs
  ln -sf $ADMINPREFS ./
  echo "Finished!"
fi

find ${BASEDIR} -name \*.dso -execdir /bin/rm {} \;

cd $BASEDIR

wine --version

echo "Running the Tribes 2 server"
xvfb-run -a -w 5 taskset -c 0 wine wine_injector.exe Server.dll Tribes2.exe ${SERVER_PORT} -dedicated -mod Classic
