#!/bin/bash

export WINEPREFIX=/home/gameserv/.wine32
export WINEARCH=win32
BASEDIR=$WINEPREFIX/drive_c/Dynamix/Tribes2/GameData

echo "Update Admin & Server Prefs..."
/tmp/tribes2/cfg-admin-prefs
echo "Finished!"

find ${BASEDIR} -name \*.dso -execdir /bin/rm {} \;

cd $WINEPREFIX/drive_c/Dynamix/Tribes2/GameData

wine --version

echo "Running the Tribes 2 server"
xvfb-run -a -w 5 taskset -c 0 wine wine_injector.exe Server.dll Tribes2.exe 28000 -dedicated -mod Classic